name: Documentation
description: Anything relating Documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
