#include "nyangine/base/base.h"

#if OS_WINDOWS
#include "nyangine/platform/clock/clock_windows.c"
#include "nyangine/platform/command/command_windows.c"
#include "nyangine/platform/filesystem/filesystem_windows.c"
#include "nyangine/platform/signals/signals_windows.c"
#elif OS_LINUX
#include "nyangine/platform/clock/clock_linux.c"
#include "nyangine/platform/command/command_linux.c"
#include "nyangine/platform/filesystem/filesystem_linux.c"
#include "nyangine/platform/signals/signals_linux.c"
#else
#error "Unsupported OS"
#endif

#include "nyangine/base/base_arena.c"
#include "nyangine/base/base_args.c"
#include "nyangine/base/base_base64.c"
#include "nyangine/base/base_build.c"
#include "nyangine/base/base_color.c"
#include "nyangine/base/base_crc.c"
#include "nyangine/base/base_error.c"
#include "nyangine/base/base_file.c"
#include "nyangine/base/base_hash.c"
#include "nyangine/base/base_integrity.c"
#include "nyangine/base/base_keys.c"
#include "nyangine/base/base_lexer.c"
#include "nyangine/base/base_logging.c"
#include "nyangine/base/base_noise.c"
#include "nyangine/base/base_object.c"
#include "nyangine/base/base_perf.c"
#include "nyangine/base/base_random.c"
#include "nyangine/base/base_string.c"
#include "nyangine/base/base_tween.c"
#include "nyangine/base/base_types.c"
#include "nyangine/base/base_uuid.c"
#include "nyangine/core/core_app.c"
#include "nyangine/core/core_asset.c"
#include "nyangine/core/core_callback.c"
#include "nyangine/core/core_entity.c"
#include "nyangine/core/core_event.c"
#include "nyangine/core/core_input.c"
#include "nyangine/core/core_job.c"
#include "nyangine/core/core_window.c"
#include "nyangine/math/math_matrix.c"
#include "nyangine/nn/nn.c"
#include "nyangine/renderer/renderer.c"
#include "nyangine/ui/ui.c"
